### ISSUE TITLE
Eigenes YForm-Value

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/flatpickr#1]
**Feature description / Feature Beschreibung**
Besteht Interesse an einem eigenen YForm-Value? Eins, das per Callback auch verfügbare Termine als Parameter übergeben kann?

**Comment by skerbis** [comment]
verfügbare und geblockte 👍🏻

**Comment by AWqxKAWERbXo** [comment]
In den nächsten 4 Wochen ist mit einem PR zu rechnen.

**Comment by AWqxKAWERbXo** [comment]
Das Versprechen konnte ich leider nicht einhalten.
